version: "3"
services:
  database:
    container_name: db
    image: mariadb:11.4
    volumes:
      - db_data:/var/lib/mysql:Z
    environment:
      MARIADB_ROOT_PASSWORD: root1234
    ports:
      - "3306:3306"
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: database
      PMA_ARBITRARY: 1
    ports:
      - "3000:80"
    depends_on:
      - database
volumes:
  db_data:
