version: "3"
services:
  eureka-server:
    container_name: eureka-server
    build: ./backends/eureka-server
    ports:
      - "8761:8761"
  player-service:
    container_name: player-svc
    build: ./backends/player-service
    ports:
      - "8081:8080"
    environment:
      - EUREKA_HOST=eureka-server
      - EUREKA_PORT=8761
      - DATABASE_URL_STRING=jdbc:mariadb://database:3306/player-svc
      - DATABASE_USER=player-svc
      - DATABASE_PASSWORD=Five0-Deepen7-Trowel4-Uncaring7
      - JWT_SECRET_KEY=353ea8909ec05ba8e47abb6a4980b714cee544652bea4f416ba60e444b476500d3ca5b51e4e1668230f04bfc098b1253025388f229c43e8e6d3c8f6c500c53db
      #- API_BASE_PATH=/api/player
      - CORS_ALLOWED_ORIGINS=http://localhost:8568
    depends_on:
      - eureka-server
      - database
      - kafka
  card-service:
    container_name: card-svc
    build: ./backends/card-service
    ports:
      - "8083:8080"
    environment:
      - EUREKA_HOST=eureka-server
      - EUREKA_PORT=8761
      - DATABASE_URL_STRING=jdbc:mariadb://database:3306/card-svc
      - DATABASE_USER=card-svc
      - DATABASE_PASSWORD=Module0-Cauterize9-Gothic8-Karaoke7
      - JWT_SECRET_KEY=353ea8909ec05ba8e47abb6a4980b714cee544652bea4f416ba60e444b476500d3ca5b51e4e1668230f04bfc098b1253025388f229c43e8e6d3c8f6c500c53db
      #- API_BASE_PATH=/api/card
      - CORS_ALLOWED_ORIGINS=http://localhost:8568
    depends_on:
      - eureka-server
      - database
      - kafka
  game-service:
    container_name: game-svc
    build: ./backends/game-service
    ports:
      - "8082:8080"
    environment:
      - EUREKA_HOST=eureka-server
      - EUREKA_PORT=8761
      - DATABASE_URL_STRING=jdbc:mariadb://database:3306/game-svc
      - DATABASE_USER=game-svc
      - DATABASE_PASSWORD=Rockslide0-Stress0-Agnostic7-Although0
      - JWT_SECRET_KEY=353ea8909ec05ba8e47abb6a4980b714cee544652bea4f416ba60e444b476500d3ca5b51e4e1668230f04bfc098b1253025388f229c43e8e6d3c8f6c500c53db
      #- API_BASE_PATH=/api/game
      - CORS_ALLOWED_ORIGINS=http://localhost:8568
    depends_on:
      - eureka-server
      - database
      - kafka
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "8568:80"
    depends_on:
      - player-service
      - card-service
      - game-service
  database:
    container_name: database
    image: mariadb:11.4
    volumes:
      - db_data:/var/lib/mysql:Z
    environment:
      MARIADB_ROOT_PASSWORD: root1234
    ports:
      - "3306:3306"
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: database
      PMA_ARBITRARY: 1
    ports:
      - "3000:80"
    depends_on:
      - database
  zookeeper:
    container_name: zookeeper
    image: bitnami/zookeeper
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
  kafka:
    container_name: kafka
    image: bitnami/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: "yes"
    depends_on:
      - zookeeper
volumes:
  db_data:
